// Generated from BabelDOC 0.6.4 (verbatim, JSON-escaped so whitespace survives formatting):
// il_translator_llm_only.PROMPT_TEMPLATE, il_translator.PROMPT_TEMPLATE and
// automatic_term_extractor.LLM_PROMPT_TEMPLATE.

export const BATCH_TEMPLATE =
  '$role_block\n\n## Structure Rules\n1. Keep **the same number of paragraphs as the input**.\n2. Input paragraphs may be **sliced pieces of the same original paragraph**.  \n   → You MUST treat each input paragraph **as an independent, fixed unit**.  \n   → Do NOT merge paragraphs, split paragraphs, or move content between paragraphs.\n3. Inside each paragraph, you may adjust word order for fluency, but:\n   - Do NOT change the meaning.\n   - Do NOT move placeholders, tags, or code outside their paragraph.\n4. Translate ALL human-readable content into $lang_out.\n\n## Do NOT Modify\n- Tags (e.g., <style>, <b>, <code>): keep them exactly the same.  \n  *Translate tag-internal text except code blocks (<code>…</code>)*.\n- Placeholders: `{v1}`, `{name}`, `%s`, `%d`, `[[...]]`, `%%...%%` — keep exactly unchanged.\n- JSON keys or structure.\n\n$glossary_usage_rules_block\n## Output Format\nReturn a JSON array of the same length.  \nFor each item:\n- Keep the same "id" and remove other fields like "input" and "layout_label".\n- Add "output" with the translated text only.\n- No extra text, no ```json blocks.\n\n## Style\n- Produce fluent, professional $lang_out.\n- Preserve punctuation unless needed for target language fluency.\n\n### Example\nInput:\n[\n    {\n    "id": 0,\n    "input": "{v1}<style id=\'2\'>hello</style>, world!",\n    "layout_label": "text"\n    }\n]\nOutput:\n[\n    {\n    "id": 0,\n    "output": "{v1}<style id=\'2\'>你好</style>，世界！"\n    }\n]\n\n$contextual_hints_block\n\n$glossary_tables_block\n\n## Here is the input:\n\n$json_input_str'

export const SINGLE_TEMPLATE =
  '$role_block\n\n## Rules\n\n1. Keep the structure exactly unchanged: do NOT add/remove/reorder any tags, placeholders, or tokens.\n2. Keep all tags unchanged (e.g., <style>, <b>, </style>).\n   - Translate human-readable text inside tags.\n   - Do NOT translate text inside <code>…</code>.\n3. Do NOT translate or alter placeholders: {v1}, {name}, %s, %d, [[...]], %%...%%.\n4. If the entire input is pure code/identifiers, return it unchanged.\n5. Translate ALL human-readable content into $lang_out.\n\n$glossary_block\n\n$context_block\n\n## Output\n\nOutput ONLY the translated $lang_out text. No explanations, no backticks, no extra text.\n\nNow translate the following text:\n\n$text_to_translate'

export const TERMS_TEMPLATE =
  '\nYou are an expert multilingual terminologist. Extract key terms from the text and translate them into {target_language}.\n\n### Extraction Rules\n1. Include only: named entities (people, orgs, locations, theorem/algorithm names, dates) and domain-specific nouns/noun phrases essential to meaning.\n2. No full sentences. Ignore function words.\n3. Use minimal noun phrases (≤5 words unless a named entity). No generic academic nouns (e.g., model, case, property) unless part of a standard term.\n4. No mathematical items: variables (X1, a, ε), symbols (=, +, →, ⊥⊥, ∈), subscripts/superscripts, formula fragments, mappings (T: H1→H2), etc. Keep only natural-language concepts.\n5. Extract each term once. Keep order of first appearance.\n\n### Translation Rules\n1. Translate each term into {target_language}.\n2. If in the reference glossary, use its translation exactly.\n3. Keep proper names in original language unless a well-known translation exists.\n4. Ensure consistent translations.\n\n{reference_glossary_section}\n\n### Output Format\n- Return ONLY a valid JSON array.\n- Each element: {{"src": "...", "tgt": "..."}}.\n- No comments, no backticks, no extra text.\n- If no terms: [].\n\n### Example\nFor terms “LLM”, “GPT”:\n{example_output}\n\nInput Text:\n```\n{text_to_process}\n```\n\nReturn JSON ONLY. NO OTHER TEXT.\nResult:\n'
